version: "2"
services:
  web:
    build: .    
    image: web
    ports:
    - 80:8080
    restart: always
    depends_on:
    - mongo    
    volumes: #comment out this section for azure docker compose deployment
    - .:/usr/src/app
    - /usr/src/app/node_modules #data volume, this saves the data when building the image, workdir, has not effect here
    networks: 
      - Net
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    restart: always
    networks: 
      - Net
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db    
volumes:
  mongodb_data_volume:
    external: true
networks: 
  Net:
    driver: bridge    
